Fix the version of hot in the demo
handsontable/docs pull request #140
Opened 2020-08-16 10:19 UTC by scarletfog

I removed a redirection to a specific link. Not sure it fixed the issue properly but locally it indeed pointed to `next`.

2020-08-18 14:59 UTC, scarletfog commented
@pnowak could you please have a look? :)

2020-09-07 10:14 UTC, budnix requested changes

2020-09-07 10:14 UTC, budnix commented on tutorials/filtering.html
> +        <button class="jsFiddleLink" data-runfiddle="example4">
Hmm, After removing the `data-link` attribute from https://handsontable.com/docs/8.0.0/demo-filtering.html page. The demo stops showing correctly in the jsfiddle. The fix requires more attention and it looks like it cannot be fixed within a single line  😉

2020-09-07 10:19 UTC, scarletfog commented on tutorials/filtering.html
> +        <button class="jsFiddleLink" data-runfiddle="example4">
I will take a look at that. Yet, I remember running the docs, maybe they were not rebuilt correctly after my changes 😅

2020-09-07 10:27 UTC, budnix commented on tutorials/filtering.html
> +        <button class="jsFiddleLink" data-runfiddle="example4">
I've tested the changes by visiting the https://handsontable.com/docs/8.0.0/demo-filtering.html page and removing the attribute from the DOM. After the "Edit in fiddle" click you'll see that fiddle is empty.

I vaguely remember that with the demo (which is written in ES6+) there was a problem with jsfiddle. The jsfiddle at that time didn't support creating fiddles with Babel support on the init. Maybe that is a reason for creating `data-link` attribute.

2020-10-14 08:55 UTC, scarletfog commented
This needs some further investigation, I will close this PR.

2020-10-14 08:55 UTC, closed without merging