Add example for comment (readonly)
handsontable/docs pull request #141
Opened 2020-08-23 15:26 UTC by scarletfog

### Context
We only mentioned cell settable as read-only when we should also tell the user that comments can be read-only as well.

https://github.com/handsontable/docs/issues/56

2020-09-08 13:18 UTC, AMBudnik requested changes
@scarletfog there's no dot after '"Honda" wording'. Besides that, everything looks good.

2020-09-08 13:45 UTC, pnowak commented on tutorials/read-only.html
> +    <div class="example-container clearfix head-gap" name="cells">
Maybe a name="comments" is more appropriate.

2020-09-08 13:45 UTC, pnowak commented on tutorials/read-only.html
> +            var container = document.getElementById('example3'),
I think that for consistency in the rest of the documents, we should use `container3`.

2020-10-15 06:54 UTC, AMBudnik approved these changes

2020-10-15 11:28 UTC, merged