Modularization page
handsontable/docs pull request #276
Opened 2021-01-07 16:12 UTC by scarletfog

### Context
Add a page about modularization, describe it, and write a tutorial.

Additionally - change the installation guide.

### Types of changes

- [ ] Bug fix (any error in documentation i.e. wrong: wording, code, links, pictures, etc.)
- [x] Improvement (better description, more examples etc.)
- [ ] Misc (any other change)

### Related issue(s):
1. https://github.com/handsontable/docs/issues/270

2021-01-08 15:08 UTC, scarletfog commented
Hi there @swistach!

I need your help here - please review the content to check if everything is correct.
Don't hesitate to push the changes if something is obviously wrong.

2021-01-08 15:50 UTC, budnix commented
I don't know but maybe it's a good idea to create a new heading section called "Build Handsontable with all batteries-included" or so. The section would contain the code with all imported a registered all possible modules. In that way, the developer could copy and paste interesting fragments into his application?

```js
import Handsontable from 'handsontable/base';
import {
  registerEditor,
  AutocompleteEditor,
  BaseEditor,
  CheckboxEditor,
  DateEditor,
  DropdownEditor,
  HandsontableEditor,
  NumericEditor,
  PasswordEditor,
  SelectEditor,
  TextEditor,
} from 'handsontable/editors';
import {
  registerRenderer,
  baseRenderer,
  autocompleteRenderer,
  checkboxRenderer,
  htmlRenderer,
  numericRenderer,
  passwordRenderer,
  textRenderer,
} from 'handsontable/renderers';
import {
  registerValidator,
  autocompleteValidator,
  dateValidator,
  numericValidator,
  timeValidator,
} from 'handsontable/validators';
import {
  registerCellType,
  AutocompleteCellType,
  CheckboxCellType,
  DateCellType,
  DropdownCellType,
  HandsontableCellType,
  NumericCellType,
  PasswordCellType,
  TextCellType,
  TimeCellType,
} from 'handsontable/cellTypes';
import {
  AutoColumnSize,
  AutoRowSize,
  Autofill,
  BasePlugin,
  BindRowsWithHeaders,
  CollapsibleColumns,
  ColumnSorting,
  ColumnSummary,
  Comments,
  ContextMenu,
  CopyPaste,
  CustomBorders,
  DragToScroll,
  DropdownMenu,
  ExportFile,
  Filters,
  Formulas,
  HeaderTooltips,
  HiddenColumns,
  HiddenRows,
  ManualColumnFreeze,
  ManualColumnMove,
  ManualColumnResize,
  ManualRowMove,
  ManualRowResize,
  MergeCells,
  MultiColumnSorting,
  MultipleSelectionHandles,
  NestedHeaders,
  NestedRows,
  ObserveChanges,
  PersistentState,
  Search,
  TouchScroll,
  TrimRows,
  UndoRedo,
  registerPlugin,
} from 'handsontable/plugins';

registerEditor(BaseEditor);
registerEditor(AutocompleteEditor);
registerEditor(CheckboxEditor);
registerEditor(DateEditor);
registerEditor(DropdownEditor);
registerEditor(HandsontableEditor);
registerEditor(NumericEditor);
registerEditor(PasswordEditor);
registerEditor(SelectEditor);
registerEditor(TextEditor);

registerRenderer(baseRenderer);
registerRenderer(autocompleteRenderer);
registerRenderer(checkboxRenderer);
registerRenderer(htmlRenderer);
registerRenderer(numericRenderer);
registerRenderer(passwordRenderer);
registerRenderer(textRenderer);

registerValidator(autocompleteValidator);
registerValidator(dateValidator);
registerValidator(numericValidator);
registerValidator(timeValidator);

registerCellType(AutocompleteCellType);
registerCellType(CheckboxCellType);
registerCellType(DateCellType);
registerCellType(DropdownCellType);
registerCellType(HandsontableCellType);
registerCellType(NumericCellType);
registerCellType(PasswordCellType);
registerCellType(TimeCellType);
registerCellType(TextCellType);

registerPlugin(AutoColumnSize);
registerPlugin(Autofill);
registerPlugin(AutoRowSize);
registerPlugin(BindRowsWithHeaders);
registerPlugin(CollapsibleColumns);
registerPlugin(ColumnSorting);
registerPlugin(ColumnSummary);
registerPlugin(Comments);
registerPlugin(ContextMenu);
registerPlugin(CopyPaste);
registerPlugin(CustomBorders);
registerPlugin(DragToScroll);
registerPlugin(DropdownMenu);
registerPlugin(ExportFile);
registerPlugin(Filters);
registerPlugin(Formulas);
registerPlugin(HeaderTooltips);
registerPlugin(HiddenColumns);
registerPlugin(HiddenRows);
registerPlugin(ManualColumnFreeze);
registerPlugin(ManualColumnMove);
registerPlugin(ManualColumnResize);
registerPlugin(ManualRowMove);
registerPlugin(ManualRowResize);
registerPlugin(MergeCells);
registerPlugin(MultiColumnSorting);
registerPlugin(MultipleSelectionHandles);
registerPlugin(NestedHeaders);
registerPlugin(NestedRows);
registerPlugin(ObserveChanges);
registerPlugin(PersistentState);
registerPlugin(Search);
registerPlugin(TouchScroll);
registerPlugin(TrimRows);

new Handsontable(container, {});
```

WDYT? @scarletfog @wojciechczerniak

2021-01-08 16:59 UTC, scarletfog commented
@budnix I think it's a good idea! @wojciechczerniak ?

2021-01-10 20:27 UTC, wojciechczerniak requested changes
@scarletfog TOC has only two items "Usefulness of modularization", "How to use modularization". We were talking about additional sections: locales, wrappers, etc. We should create more sections. Also, we're talking about optimizing moment.js languages but does not explain how to do that. I would link all sections here.

```
"Usefulness of modularization"
"How to use modularization"
"Importing plugins"
"Importing editors"
"Importing renderers"
"Importing validators"
"Importing cell types"
"Importing locales"
"Optimizing moment.js locales"
"Using with wrappers"
"Tree shaking"
```

I would move the graph higher. We have too much code in the first section. Two examples with a configuration that may be not relevant to modularization.

@budnix @scarletfog Good idea. Easy for copy&paste. But maybe we should hide it in a collapsible `<detail>` tag? This page is very long as it is now.

2021-01-10 20:27 UTC, wojciechczerniak commented on tutorials/modularization.html
> +new Handsontable(container, {
The container takes a big part of the example, we should remove those lines.

2021-01-10 20:27 UTC, wojciechczerniak commented on tutorials/modularization.html
> +import { plPL} from 'handsontable/i18n/languages';
```suggestion
import {plPL} from 'handsontable/i18n/languages';
```

2021-01-10 20:27 UTC, wojciechczerniak commented on tutorials/modularization.html
> +registerPlugin(Filter
```suggestion
registerPlugin(Filters);
```

2021-01-12 15:14 UTC, scarletfog commented
@wojciechczerniak more splitting into sections like I initially did? https://github.com/handsontable/docs/pull/276/commits/ca8daa6e59ba9d6659398477b30e59c682675f0a 

I had some second thoughts (as this is repeating a similar pattern, so they pretty much go under the "how to use modularization" section, etc.) but I can make them separate again. 

I am not quite sure about the collapsible detail tag - it can be overlooked easily. On the other hand, though, the list takes _a lot_ of space...

2021-01-13 11:06 UTC, wojciechczerniak commented
> @wojciechczerniak more splitting into sections like I initially did? [ca8daa6](https://github.com/handsontable/docs/commit/ca8daa6e59ba9d6659398477b30e59c682675f0a)
> 
> I had some second thoughts (as this is repeating a similar pattern, so they pretty much go under the "how to use modularization" section, etc.) but I can make them separate again.

Looks good. In the new markdown docs this TOC will be generated from the headers anyway. So will look more or less like that.
 
> I am not quite sure about the collapsible detail tag - it can be overlooked easily. On the other hand, though, the list takes _a lot_ of space...

True. One of the ideas to make it more visible but still collapsed is to show just 10 first lines of the example, the rest fading away, and the "expand more" button. But that would require some work.

2021-01-13 15:48 UTC, warpech requested changes

2021-01-13 15:48 UTC, warpech commented on tutorials/modularization.html
> +      The full version of Handsontable consists of multiple built-in modules such as plugins, renderers, editors, validators, and cell-types.
In our technical communication it's called "full distribution" not "full version", see https://github.com/handsontable/handsontable/blob/master/dist/README.md

Nowadays, a "full bundle" or "full build" would be a more popular name, but not "full version".

2021-01-13 15:48 UTC, warpech commented on tutorials/modularization.html
> +    <h3 id="introduction">Usefulness of modularization</h3>
Modularization is, as Aaron wrote in his blog post:

> the process of turning things that are not modules… into modules. 

So it is the right name for the project or for a blog post about that project. But once we have modules, the name for a page in the docs should be "Modules" or "Using modules", or "Importing by modules". It is just a way of installation that is an alternative to "Importing a full distribution".

See the same in other systems:

- https://www.ag-grid.com/documentation/javascript/modules/
- https://angular.io/guide/architecture-modules
- https://docs.anychart.com/Quick_Start/Modules
- https://www.amcharts.com/docs/v4/getting-started/basics/#Modules (here modules are just a part of the installation page)

2021-01-14 14:44 UTC, wojciechczerniak commented on tutorials/modularization.html
> +      The full version of Handsontable consists of multiple built-in modules such as plugins, renderers, editors, validators, and cell-types.
Agree. "Full version" suggests that there is some kind non-full version, limited, trial, demo. I think "bundle" would be the most precise technical term here.

2021-01-14 14:46 UTC, wojciechczerniak commented on tutorials/modularization.html
> +    <h3 id="introduction">Usefulness of modularization</h3>
True. The process of modularization has ended. We can argue that our clients have to go through the process in their apps, but it's simpler and clearer to just call it Modules.

2021-01-18 15:47 UTC, scarletfog commented on tutorials/modularization.html
> +    <h3 id="introduction">Usefulness of modularization</h3>
True! I changed the wording here: https://github.com/handsontable/docs/pull/276/commits/366b1aac741510e95ee6b1f302bd0b612916e2ca

2021-01-18 15:51 UTC, scarletfog commented on tutorials/modularization.html
> +      The full version of Handsontable consists of multiple built-in modules such as plugins, renderers, editors, validators, and cell-types.
I used the word "bundle" https://github.com/handsontable/docs/pull/276/commits/366b1aac741510e95ee6b1f302bd0b612916e2ca 

but I have a question - should we also change the "distribution" into "bundle" here (or make it the other way round)? https://github.com/handsontable/handsontable/blob/master/dist/README.md

Maybe it could be good to have this consistent?

2021-01-18 16:42 UTC, wojciechczerniak commented on tutorials/modularization.html
> +      The full version of Handsontable consists of multiple built-in modules such as plugins, renderers, editors, validators, and cell-types.
If you have a minute to push it then we should. Good idea, consistency is a good thing

2021-01-18 17:47 UTC, wojciechczerniak requested changes

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +     You can compare the following examples to see the difference in KB of the final build.
```suggestion
     You can compare the following examples to see the difference in the size of the final build.
```

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +document.body.appendChild(container);
The container is irrelevant here

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +});
I have an idea, we could extract the settings from both examples.
```suggestion
const hot = new Handsontable(container, settings);
```

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +});
```suggestion
const hot = new Handsontable(container, settings);
```

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +     <pre><code class="lang-js">
And add the settings somewhere here:

```suggestion
    </p>
    
<pre><code class="lang-js">
  const settings =  {
  colHeaders: true,
  filters: true,
  data: [
    {
      city: "Fontainebleau",
      country: "France",
    },
    {
      city: "Milton",
      country: "United Kingdom",
    },
    {
      city: "Giedlarowa",
      country: "Poland",
    },
    {
      city: "Forssa",
      country: "Finland",
    },
    {
      city: "Halle",
      country: "Germany",
    }
  ],
  dropdownMenu: true,
  columns: [
    { data: 'city' },
    {
      data: 'country',
      type: 'dropdown',
      source: ['Finland', 'France', 'Germany', 'Poland', 'United Kingdom'],
    },
  ]
}
    </code></pre>
    
    <p>As you can see, few plugins are used here: filter, dropdownMenu. We can import default Handsontable class which will include full bundle and they will be included:</p>
    
     <pre><code class="lang-js"> ... </code></pre>
     
     <p>But this will load more plugins that we don;t need. Or we can use `handsontable/base` and load only the plugins that ... 
```

WDYT?

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +  filters: true,
`filters` are used twice in the settings object, please review them all

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +registerEditor(PasswordEditor);
```suggestion
import { registerEditor, PasswordEditor } from 'handsontable/editors';

registerEditor(PasswordEditor);
```

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +registerRenderer(autocompleteRenderer);
```suggestion
import { registerRenderer, autocompleteRenderer } from 'handsontable/renderers';

registerRenderer(autocompleteRenderer);
```

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +registerValidator(numericValidator);
```suggestion
import { registerValidator, numericValidator } from 'handsontable/validators';

registerValidator(numericValidator);
```

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +import { registerCellType, CheckboxCellType } from 'handsontable/cellTypes';
Some examples have a new line, some doesn't. Dunno which formatting convention you wan to use
```suggestion
// remember to have the base imported
import Handsontable from 'handsontable/base';
// import the method for registering a cell type
// import the CheckboxCellType
import { registerCellType, CheckboxCellType } from 'handsontable/cellTypes';
```

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +import { plPL} from 'handsontable/i18n/languages';
```suggestion
import { plPL } from 'handsontable/i18n/languages';
```

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +import {plPL} from 'handsontable/i18n/languages';
Most of the imports have space between curly brackets

```suggestion
import { plPL } from 'handsontable/i18n/languages';
```

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +    </p>
We're missing Handsontable in this context. If I remember correctly, the moment and locale registration should be done before importing Handsontable, so Handsontable will use that moment.js context.

CC @swistach Can you tell us what could be added here to have a fully functional example?

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +    <p>In general, we re-export plugins, renderers, editors, validators, and cell types in the second level of package depth.</p>
Right... but why? How is this related to tree shaking. Do we support it or not, and how the mentioned bundles will handle it.

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +    <p>In general, we re-export plugins, renderers, editors, validators, and cell types in the second level of package depth.</p>
Looks weird when we have a single sentence in each of the 3 paragraphs.

2021-01-18 17:47 UTC, wojciechczerniak commented on tutorials/modules.html
> +    <p>Here is an extensive list of all Handsontable parts imported and registered. This example builds Handsontable out of all fragments. You can copy and CopyPaste
We're not talking about plugin here
```suggestion
    <p>Here is an extensive list of all Handsontable parts imported and registered. This example builds Handsontable out of all fragments. You can copy and ???
```

2021-01-19 10:05 UTC, scarletfog commented on tutorials/modules.html
> +    <p>Here is an extensive list of all Handsontable parts imported and registered. This example builds Handsontable out of all fragments. You can copy and CopyPaste
Oh VSC thank you for being so supportive when it comes to suggestions 🙄 

I probably meant that developers can copy and paste the parts of the example they need...

2021-01-19 10:06 UTC, scarletfog commented on tutorials/modules.html
> +     <pre><code class="lang-js">
Good idea, less noise

2021-01-19 13:40 UTC, scarletfog commented on tutorials/modules.html
> +  filters: true,
checked. Now, I see only one occurrence of `filters`

2021-01-19 13:55 UTC, wojciechczerniak commented on tutorials/modules.html
> +    <p>In general, we re-export plugins, renderers, editors, validators, and cell types in the second level of package depth.</p>
From @budnix 

**Note:** For Webpack 3 and older, Parcel, maybe few other bundlers that are loading CommonJS modules, for the Tree Shaking to work correctly you can't import plugins from a single file `handsontable/plugins` as demonstrated above. Those imports have to be split into importing selected modules one by one from their respective files.

```ts
import { registerPlugin } from 'handsontable/plugins/registry';
import { DropdownMenu } from 'handsontable/plugins/dropdownMenu';
import { ContextMenu } from 'handsontable/plugins/contextMenu';
```

2021-01-19 13:56 UTC, scarletfog commented on tutorials/modules.html
> +    <p>In general, we re-export plugins, renderers, editors, validators, and cell types in the second level of package depth.</p>
I think this is the only info I got from @swistach - so I need some help here 🔔

2021-01-20 11:53 UTC, swistach commented on tutorials/modules.html
> +    </p>
Yes, it has to be done before we import Handsontable.
I prefer to use ESM in examples so it might look like:
```
import moment from 'moment';
import 'moment/locale/ja';
import Handsontable from 'handsontable/base';
import { registerCellType, DateCellType } from 'handsontable/cellTypes';

moment.locale('ja');
registerCellType(DateCellType);

new Handsontable(container, {
  type: 'date',
});
```

2021-01-20 11:53 UTC, swistach commented on tutorials/modules.html
> +    <p>In general, we re-export plugins, renderers, editors, validators, and cell types in the second level of package depth.</p>
Ok, so to clarify things:
`tree shaking` aka `death code elimination` it's something that modern bundlers does out-of-the-box when end-developer builds an app for production.
Even if by default, CJS is the non-shakeable(?) format - there are 3rd party plugins to bundlers, which helps in eliminating as much as possible from the final bundle.
This point in my mind at the creation time (a month ago) was an idea to let end-developers a quick reference to the tools' documentation they probably use.
I've been thinking about it more like helpful "read more" section than a standalone paragraph with important content - at this moment it seems to be irrelevant and we can remove it entirely or just left links to bundlers docs.

2021-01-20 11:53 UTC, swistach commented on tutorials/modules.html
> +      <img src="images/modularization_comparison1.png" alt="modularization_comparison_graph" />
I'm not sure if the simplified legend for X axe on a chart describes what we wanted to point.
`Full build` and `Optimized` are fine (maybe instead of "Optimized" we should use "Selective modules"?) but `With optimized locales` is misnaming.
We do not point what `locales` are not optimized - at the moment it looks like our i18n module is not optimized.
I think we should bold the information that momentjs' configuration needs some additional configuration :)

2021-01-21 08:57 UTC, budnix commented on tutorials/modules.html
> +      <img src="images/modularization_comparison1.png" alt="modularization_comparison_graph" />
The same as the Suspend Rendering issue I'd change the image size https://github.com/handsontable/docs/pull/267#discussion_r560955522

2021-01-21 09:25 UTC, budnix commented on tutorials/modules.html
> +import Handsontable from 'handsontable',
```suggestion
import Handsontable from 'handsontable';
```

2021-01-21 09:25 UTC, budnix commented on tutorials/modules.html
> +registerCellType(CheckboxCellType);
```suggestion
import { registerCellType, CheckboxCellType } from 'handsontable/cellTypes';

registerCellType(CheckboxCellType);
```

2021-01-21 09:25 UTC, budnix commented on tutorials/modules.html
> +import { plPL } from 'handsontable/i18n/languages';
For a modularized version, I'd recommend using the i18n module `import { registerLanguageDictionary } from 'handsontable/i18n';`. The API is consistent with other importable modules. In the future the i18n module can be modularized as well (right now it's build-in into Base) without breaking change - I suppose.

2021-01-21 09:25 UTC, budnix commented on tutorials/modules.html
> +Handsontable.languages.registerLanguageDictionary(plPL.languageCode, plPL);
I'd use the modularized version of the language registration (ref https://github.com/handsontable/docs/pull/276/files#r560862544).

```suggestion
import Handsontable from 'handsontable/base';
import { registerLanguageDictionary } from 'handsontable/i18n';
import { plPL } from 'handsontable/i18n/languages';

registerLanguageDictionary(plPL);
```

2021-01-21 09:25 UTC, budnix commented on tutorials/modules.html
> +registerPlugin(TrimRows);
Add missing UndoRedo plugin :)
```suggestion
registerPlugin(TrimRows);
registerPlugin(UndoRedo);
```

2021-01-21 09:45 UTC, wojciechczerniak commented on tutorials/modules.html
> +import { plPL } from 'handsontable/i18n/languages';
I think we should use modules now and in the future. Slowly replace all the UMD uses in the documentation.

@swistach UMD could be another tab in code snippet switcher, but even that might be too much. I don't know if we should take user focus from frameworks. And probably if we were going to add more tabs, we have ideas that bring more value to the table. Maybe a dedicated page just for UMD then?

2021-01-21 09:50 UTC, wojciechczerniak commented on tutorials/modules.html
> +      <img src="images/modularization_comparison1.png" alt="modularization_comparison_graph" />
@swistach Wasn't that your chart proposal? :) Maybe you can mock a better one? I'm not sure if the moment.js should be even there. We can keep the section about it as "more ideas to optimize your app" because moment.js weight is "not on us" (but it is since it was our choice).

2021-01-21 10:06 UTC, budnix commented
Referring to https://github.com/handsontable/docs/pull/276/files#r560192050. Here I'm pasting the available modules which can be imported selectively.

In some cases, importing specific modules can drop the resulting bundle size even more. Generally, it depends on the environment where the code is built from.

```js
import { registerEditor } from 'handsontable/editors/registry';
import { AutocompleteEditor } from 'handsontable/editors/autocompleteEditor';
import { BaseEditor } from 'handsontable/editors/baseEditor';
import { CheckboxEditor } from 'handsontable/editors/checkboxEditor';
import { DateEditor } from 'handsontable/editors/dateEditor';
import { DropdownEditor } from 'handsontable/editors/dropdownEditor';
import { HandsontableEditor } from 'handsontable/editors/handsontableEditor';
import { NumericEditor } from 'handsontable/editors/numericEditor';
import { PasswordEditor } from 'handsontable/editors/passwordEditor';
import { SelectEditor } from 'handsontable/editors/selectEditor';
import { TextEditor } from 'handsontable/editors/textEditor';

import { registerCellType } from 'handsontable/cellTypes/registry';
import { AutocompleteCellType } from 'handsontable/cellTypes/autocompleteType';
import { CheckboxCellType } from 'handsontable/cellTypes/checkboxType';
import { DateCellType } from 'handsontable/cellTypes/dateType';
import { DropdownCellType } from 'handsontable/cellTypes/dropdownType';
import { HandsontableCellType } from 'handsontable/cellTypes/handsontableType';
import { NumericCellType } from 'handsontable/cellTypes/numericType';
import { PasswordCellType } from 'handsontable/cellTypes/passwordType';
import { TextCellType } from 'handsontable/cellTypes/textType';
import { TimeCellType } from 'handsontable/cellTypes/timeType';

import { registerPlugin } from 'handsontable/plugins/registry';
import { AutoColumnSize } from 'handsontable/plugins/autoColumnSize';
import { Autofill } from 'handsontable/plugins/autofill';
import { autoRowSize } from 'handsontable/plugins/autoRowSize';
import { BasePlugin } from 'handsontable/plugins/base';
import { BindRowsWithHeaders } from 'handsontable/plugins/bindRowsWithHeaders';
import { CollapsibleColumns } from 'handsontable/plugins/collapsibleColumn';
import { ColumnSorting } from 'handsontable/plugins/columnSorting';
import { Comments } from 'handsontable/plugins/comments';
import { ContextMenu } from 'handsontable/plugins/contextMenu';
import { CopyPaste } from 'handsontable/plugins/copyPaste';
import { CustomBorders } from 'handsontable/plugins/customBorders';
import { DragToScroll } from 'handsontable/plugins/dragToScroll';
import { DropdownMenu } from 'handsontable/plugins/dropdownMenu';
import { ExportFile } from 'handsontable/plugins/exportFile';
import { Filters } from 'handsontable/plugins/filters';
import { HeaderTooltips } from 'handsontable/plugins/headerTooltips';
import { HiddenColumns } from 'handsontable/plugins/hiddenColumns';
import { HiddenRows } from 'handsontable/plugins/hiddenRows';
import { ManualColumnFreeze } from 'handsontable/plugins/manualColumnFreeze';
import { ManualColumnMove } from 'handsontable/plugins/manualColumnMove';
import { ManualColumnResize } from 'handsontable/plugins/manualColumnResize';
import { ManualRowMove } from 'handsontable/plugins/manualRowMove';
import { ManualRowResize } from 'handsontable/plugins/manualRowResize';
import { MergeCells } from 'handsontable/plugins/mergeCells';
import { MultipleSelectionHandles } from 'handsontable/plugins/multipleSelectionHandles';
import { NestedHeaders } from 'handsontable/plugins/nestedHeaders';
import { NestedRows } from 'handsontable/plugins/nestedRows';
import { ObserveChanges } from 'handsontable/plugins/observeChanges';
import { PersistentState } from 'handsontable/plugins/persistentState';
import { Search } from 'handsontable/plugins/search';
import { TouchScroll } from 'handsontable/plugins/touchScroll';
import { TrimRows } from 'handsontable/plugins/trimRows';
import { UndoRedo } from 'handsontable/plugins/undoRedo';

import { registerRenderer } from 'handsontable/renderers/registry';
import { autocompleteRenderer } from 'handsontable/renderers/autocompleteRenderer';
import { baseRenderer } from 'handsontable/renderers/baseRenderer';
import { checkboxRenderer } from 'handsontable/renderers/checkboxRenderer';
import { htmlRenderer } from 'handsontable/renderers/htmlRenderer';
import { numericRenderer } from 'handsontable/renderers/numericRenderer';
import { passwordRenderer } from 'handsontable/renderers/passwordRenderer';
import { textRenderer } from 'handsontable/renderers/textRenderer';

import { registerValidator } from 'handsontable/validators/registry';
import { autocompleteValidator } from 'handsontable/validators/autocompleteValidator';
import { dateValidator } from 'handsontable/validators/dateValidator';
import { numericValidator } from 'handsontable/validators/numericValidator';
import { timeValidator } from 'handsontable/validators/timeValidator';


```

2021-01-21 15:28 UTC, scarletfog commented on tutorials/modules.html
> +      <img src="images/modularization_comparison1.png" alt="modularization_comparison_graph" />
@wojciechczerniak yup, maybe we should skip moment.js optimization in the chart, we can still mention it in the paragraph aaand... we have a section about this.

@swistach WDYT? + please prepare s sketch of the chart that includes the changes you suggest.

2021-01-21 15:46 UTC, scarletfog commented on tutorials/modules.html
> +import { plPL } from 'handsontable/i18n/languages';
Changed below, please check if I did not mess anything up.

2021-01-21 16:18 UTC, wojciechczerniak commented
@scarletfog Don't you have the list twice now? Maybe we could choose just one syntax?

2021-01-22 13:16 UTC, budnix commented
> @budnix could you please check if this change [5308f81](https://github.com/handsontable/docs/commit/5308f8116bd1b9c0fabda43daf8bf2ab727e24d3) is what you meant in the comment :)

It's great! I liked the idea that the code is hidden under the `details` tag 👍 

I have one more question. @wojciechczerniak Should we mention that the CSS files aren't modularized and no matter what plugin the developer uses the "full" CSS from dist/ has to be imported.

2021-01-22 13:42 UTC, wojciechczerniak commented
@budnix @scarletfog Definitely! Thanks for reminding me. CSS is a very important aspect and the way it works with modules should be explained to avoid any misunderstanding or problems for our users.

2021-01-22 15:35 UTC, scarletfog commented
@budnix @wojciechczerniak this line, right?
```
import 'handsontable/dist/handsontable.full.css';
```

2021-01-22 15:55 UTC, scarletfog commented
And do you think this change is sufficient https://github.com/handsontable/docs/pull/276/commits/b996cc2fcc754075fee7e6704325b1e6f2231ed9 or/and we should also write about this in the paragraph (maybe add in each example?)

2021-01-22 16:51 UTC, wojciechczerniak requested changes
🏆

2021-01-22 16:51 UTC, wojciechczerniak commented on tutorials/modules.html
> +      <summary>See the full list</summary>
Nice! But we will need some CSS to make it more visible. Currently, it's not that obvious you can click on it, looks like plain text. The cursor also does not indicate it's a clickable element.

2021-01-25 16:15 UTC, warpech commented on tutorials/modules.html
> +    <p>In general, we re-export plugins, renderers, editors, validators, and cell types in the second level of package depth.</p>
I don't know, looks like BBC :) https://www.bbc.com/news/technology-55625071

2021-01-25 16:17 UTC, warpech commented on tutorials/modularization.html
> +    <h3 id="introduction">Usefulness of modularization</h3>
Thanks, this is what I meant! Resolving as done

2021-01-25 16:19 UTC, warpech commented on tutorials/modularization.html
> +      The full version of Handsontable consists of multiple built-in modules such as plugins, renderers, editors, validators, and cell-types.
I agree with using the word bundle there as well. If you can't do it immediately, maybe make an issue there?

2021-01-26 08:14 UTC, scarletfog commented on tutorials/modularization.html
> +      The full version of Handsontable consists of multiple built-in modules such as plugins, renderers, editors, validators, and cell-types.
Well, I forgot about this case...
The issue was created here: https://github.com/handsontable/docs/issues/280

2021-01-26 08:17 UTC, wojciechczerniak approved these changes
🎖️

2021-01-26 08:42 UTC, merged