Add HyperFormula plugin docs
handsontable/docs pull request #312
Opened 2021-05-25 10:16 UTC by nikersify

### Context
This PR adds documentation for the new formulas plugin to be added in 9.0.

The used `jsdoc` is still based on https://github.com/handsontable/handsontable/tree/feature/hyperformula-2021 where the `dist` folder is not updated yet, to build the documentation I did something along the lines of:

```bash
cd [handsontable#feature/hyperformula-2021]
npm install
npm run build

cd [docs]
npm install
npm run start -- --hot-version=feature/hyperformula-2021
npm run build:next
rm -rf generated/components/handsontable/dist
cp -r [handsontable#feature/hyperformula-2021]/dist generated/components/handsontable/dist
```

cc @jansiegel @budnix @wojciechczerniak @krzysztofspilka 

### Related issue(s):
1. https://github.com/handsontable/handsontable/issues/8074

2021-05-25 11:27 UTC, budnix commented
The formulas with an example related to "Data grid example" are misaligned:
![Kapture 2021-05-25 at 13 26 22](https://user-images.githubusercontent.com/571316/119490287-f3366000-bd5c-11eb-88f4-e05248e05100.gif)

2021-05-25 11:41 UTC, budnix commented on tutorials/hyperformula-integration.html
> +  }
Here I'd add some config examples from HyperFormula. It's easier to learn from examples. So something like:
```suggestion
  formulas: {
    engine: {
      hyperformula: HyperFormula, // or `engine: hyperformulaInstance`
      leapYear1900: false,
      binarySearchThreshold: 15,
      // ... and more configuration options. See https://handsontable.github.io/hyperformula/api/interfaces/configparams.html#number 
    },
    // [plugin configuration]
  }
```

2021-05-25 11:51 UTC, budnix commented on tutorials/hyperformula-integration.html
> +    sheetName: 'Sheet 2'
Probably it's safer not to use special characters. In this case an empty space. 
```suggestion
    sheetName: 'Sheet2'
```

2021-05-25 11:52 UTC, budnix commented on tutorials/hyperformula-integration.html
> +        <li><a href="/docs/next/Formulas.html">Plugin API reference</a></li>
```suggestion
        <li><a href="/docs/<?js= version ?>/Formulas.html">Plugin API reference</a></li>
```

2021-05-25 14:02 UTC, nikersify commented
> The formulas with an example related to "Data grid example" are misaligned:

Fixed in https://github.com/handsontable/docs/pull/312/commits/7d0eea49c9fdbff2a8425a21c42a9bd2d0e963dc

2021-05-26 09:09 UTC, wojciechczerniak commented on tutorials/migration-guide.html
> +        </tr>
```suggestion
        <tr>
          <td><a href="https://handsontable.com/docs/8.4.0/Formulas.html#recalculate"><code>recalculate</code></a></td>
          <td><code>hot.getPlugin('formulas').recalculate()</code></td>
          <td><code>hot.getPlguin('formulas').engine.rebuildAndRecalculate()</code></td>
        </tr>
        <tr>
          <td><a href="https://handsontable.com/docs/8.4.0/Formulas.html#recalculateFull"><code>recalculateFull</code></a></td>
          <td><code>hot.getPlugin('formulas').recalculateFull()</code></td>
          <td><code>hot.getPlguin('formulas').engine.rebuildAndRecalculate()</code></td>
        </tr>
        <tr>
          <td><a href="https://handsontable.com/docs/8.4.0/Formulas.html#recalculateOptimized"><code>recalculateOptimized</code></a></td>
          <td><code>hot.getPlugin('formulas').recalculateOptimized()</code></td>
          <td><code>hot.getPlguin('formulas').engine.rebuildAndRecalculate()</code></td>
        </tr>
```

2021-05-26 09:17 UTC, budnix commented on tutorials/hyperformula-integration.html
> +    sheetName: 'Sheet 1'
```suggestion
    sheetName: 'Sheet1'
```

2021-05-26 09:17 UTC, budnix commented on tutorials/hyperformula-integration.html
> +    sheetName: 'Sheet 1'
```suggestion
    sheetName: 'Sheet1'
```

2021-05-26 09:18 UTC, budnix commented on tutorials/hyperformula-integration.html
> +    sheetName: 'Sheet 2'
```suggestion
    sheetName: 'Sheet2'
```

2021-05-26 09:27 UTC, budnix commented on tutorials/hyperformula-integration.html
> +          ['How many blank cells are in the Sheet1?', '=COUNTBLANK(Sheet1!A1:E5)'],
```suggestion
          ['How many blank cells are in the Sheet1?', '=COUNTBLANK(Sheet1!A1:D5)'],
```
The first sheet has only 4 columns defined

2021-05-26 09:30 UTC, budnix commented on tutorials/hyperformula-integration.html
> +        ];
`COUNTBLANK` does not count an empty strings so for better number representation I suggest to change the date of the second column.
```suggestion
        var data1 = [
          ['10.26', null, 'Sum', '=SUM(A:A)'],
          ['20.12', null, 'Average', '=AVERAGE(A:A)'],
          ['30.01', null, 'Median', '=MEDIAN(A:A)'],
          ['40.29', null, 'MAX', '=MAX(A:A)'],
          ['50.18', null, 'MIN', '=MIN(A:A)'],
        ];
```

2021-05-26 09:34 UTC, budnix commented on tutorials/hyperformula-integration.html
> +          height: 500
I think that the demo looks better when all columns are stretched. My suggestion:
```suggestion
          fixedRowsBottom: 2,
          stretchH: 'all',
          height: 500
```

2021-05-26 10:04 UTC, nikersify commented on tutorials/hyperformula-integration.html
> +          height: 500
Yup, much better

2021-05-26 10:28 UTC, wojciechczerniak requested changes

2021-05-26 10:28 UTC, wojciechczerniak commented on tutorials/migration-guide.html
> +      <h3>Migrating from 8 to 9</h3>
Missing:
- migration guide for `beforeAutofill`, `afterAutofill` with use cases
- migration guide for `tooltipPlugin` with alternative way to implement this
- migration guide for `observeChanges` plugin, not needed, index mappers should be notified

2021-05-26 10:28 UTC, wojciechczerniak commented on tutorials/migration-guide.html
> +}</code></pre>
HyperFormula has to be imported first. This is important

 For UMD should be in global scope.

2021-05-26 10:28 UTC, wojciechczerniak commented on tutorials/migration-guide.html
> +        </tr>
Those are standard methods for each plugin in HOT and should be used internally only. IMO we should not mention them publicly i work toward hiding them from public APIs

2021-05-26 10:28 UTC, wojciechczerniak commented on tutorials/migration-guide.html
> +        </tr>
We should not expose the `engine` like that. IMO the engine should be internal whenever possible

2021-05-26 10:28 UTC, wojciechczerniak commented on tutorials/formula-support.html
> +  <div class="notification warning">This plugin has been permanently replaced with the new one in version 9.0. Please upgrade your Handsontable version to use the <a href="/docs/next/demo-hyperformul
I get that we want new page but IMO we should remove old page and add a redirect

2021-05-26 10:28 UTC, wojciechczerniak commented on tutorials/hyperformula-integration.html
> +      For the list of available settings and methods, visit the <a href="/docs/next/Formulas.html">API reference</a>.
Next?
```suggestion
      For the list of available settings and methods, visit the <a href="/docs/???/Formulas.html">API reference</a>.
```

Do we even have this page? It's marked as deprecated and the list or API are not updated

2021-05-26 10:29 UTC, wojciechczerniak commented on tutorials/hyperformula-integration.html
> +    sheetName: 'Sheet 1'
Why? The `Sheet 1` is a valid name and I think that HF will generate them like that

2021-05-26 10:34 UTC, wojciechczerniak requested changes

2021-05-26 10:34 UTC, wojciechczerniak commented on tutorials/hyperformula-integration.html
> +          ['50.18', null, 'MIN', '=MIN(A:A)'],
@budnix showed in https://github.com/handsontable/handsontable/issues/8104 that this example does not work. Should use not implemented features to showcase new plugin?

2021-05-26 10:34 UTC, wojciechczerniak commented on tutorials/hyperformula-integration.html
> +    sheetName: 'Sheet 1'
Ok, I see that some formulas are using `Sheet1!A1` references. But it may be fixed as well

2021-05-26 10:37 UTC, budnix commented on tutorials/hyperformula-integration.html
> +      For the list of available settings and methods, visit the <a href="/docs/next/Formulas.html">API reference</a>.
Each `/next/` version should be replaced with `/<?js= version ?>/`.

2021-05-26 11:20 UTC, nikersify commented on tutorials/migration-guide.html
> +        </tr>
Sure they are standard, but at least `enablePlugin()` did change enough that it should a mention, I think.

2021-05-26 11:22 UTC, nikersify commented on tutorials/migration-guide.html
> +}</code></pre>
The text right above already should explain that, isn't that enough?

2021-05-26 11:24 UTC, nikersify commented on tutorials/formula-support.html
> +  <div class="notification warning">This plugin has been permanently replaced with the new one in version 9.0. Please upgrade your Handsontable version to use the <a href="/docs/next/demo-hyperformul
This is per the docx draft, cc @krzysztofspilka

2021-05-26 11:41 UTC, nikersify commented on tutorials/hyperformula-integration.html
> +      For the list of available settings and methods, visit the <a href="/docs/next/Formulas.html">API reference</a>.
@budnix Even the one in `formula-support.html`? Wouldn't that make users looking at doc versions <9.0.0 404?

2021-05-26 11:47 UTC, nikersify commented on tutorials/hyperformula-integration.html
> +          ['50.18', null, 'MIN', '=MIN(A:A)'],
Interesting, https://github.com/handsontable/docs/pull/312/commits/12dbbd8b04d0c5e137fe063187e0fe9415520325

2021-05-26 11:50 UTC, budnix commented on tutorials/hyperformula-integration.html
> +      For the list of available settings and methods, visit the <a href="/docs/next/Formulas.html">API reference</a>.
In that case, the `formula-support.html` page should link to the latest version of the documentation where the old Formulas was supported, I guess.

2021-05-26 12:21 UTC, wojciechczerniak commented on tutorials/migration-guide.html
> +            "Variables" in the plugin have been replaced by a more powerful alternative, <a href="/docs/next/demo-hyperformula-integration.html#named-expressions"><i>named expressions</i></a>
```suggestion
            "Variables" in the plugin have been replaced by a more powerful alternative, <a href="/docs/???/demo-hyperformula-integration.html#named-expressions"><i>named expressions</i></a>
```

2021-05-26 12:22 UTC, wojciechczerniak commented on tutorials/migration-guide.html
> +            "Variables" in the plugin have been replaced by a more powerful alternative, <a href="/docs/next/demo-hyperformula-integration.html#named-expressions"><i>named expressions</i></a>
```suggestion
            "Variables" in the plugin have been replaced by a more powerful alternative, <a href="/docs/???/demo-hyperformula-integration.html#named-expressions"><i>named expressions</i></a>
```

2021-05-26 12:24 UTC, wojciechczerniak commented on tutorials/hyperformula-integration.html
> +      For the list of available settings and methods, visit the <a href="/docs/next/Formulas.html">API reference</a>.
I why do we link to the old documentation for "available options and methods" ? New plugins should have it's own reference

2021-05-26 12:31 UTC, wojciechczerniak commented on tutorials/migration-guide.html
> +        </tr>
Yeah, too late for hiding interfaces, we got them so they should have a mention

2021-05-26 12:43 UTC, nikersify commented on tutorials/migration-guide.html
> +            "Variables" in the plugin have been replaced by a more powerful alternative, <a href="/docs/next/demo-hyperformula-integration.html#named-expressions"><i>named expressions</i></a>
https://github.com/handsontable/docs/pull/312/commits/38ffc3f1d8ea5e4836f72df3128384f36f25827d

2021-05-26 12:43 UTC, nikersify commented on tutorials/migration-guide.html
> +            "Variables" in the plugin have been replaced by a more powerful alternative, <a href="/docs/next/demo-hyperformula-integration.html#named-expressions"><i>named expressions</i></a>
https://github.com/handsontable/docs/pull/312/commits/38ffc3f1d8ea5e4836f72df3128384f36f25827d

2021-05-26 12:44 UTC, nikersify commented on tutorials/hyperformula-integration.html
> +      For the list of available settings and methods, visit the <a href="/docs/next/Formulas.html">API reference</a>.
Actually, I was only referring the new notification popup https://github.com/handsontable/docs/pull/312/files#diff-0d66ee487cccbbeb169b541cc2dc653567bfe5c99820230121dceaf6e6d3c4b2R2 - that page viewed on, say, 8.0.0 would always lead to a 404 if the link there was `/docs/<?=js version ?>/demo-hyperformula-integration.html` (such as https://handsontable.com/docs/8.0.0/demo-gantt-chart.html is a 404 but https://handsontable.com/docs/1.14.0/demo-gantt-chart.html isn't).

I'll just change it to a constant 9.0.0 as the first version that does include `demo-hyperformula-integration.html`, I hope this will be fine.

https://github.com/handsontable/docs/pull/312/commits/38ffc3f1d8ea5e4836f72df3128384f36f25827d

2021-05-26 14:20 UTC, nikersify commented on tutorials/migration-guide.html
> +      <h3>Migrating from 8 to 9</h3>
@jansiegel

2021-06-01 07:48 UTC, budnix approved these changes

2021-06-01 09:53 UTC, nikersify commented on tutorials/migration-guide.html
> +      <h3>Migrating from 8 to 9</h3>
and the rest https://github.com/handsontable/docs/pull/312/commits/5f4e6b6e20733ec2c0e6294515ed794759964d64

2021-06-01 10:15 UTC, wojciechczerniak approved these changes
👍

2021-06-01 10:15 UTC, wojciechczerniak commented on tutorials/migration-guide.html
> +          <li><a href="#9.0.0-removed-plugins">Removed plugins</a></li>
Can we move plugins sections up in the hierarchy?

```suggestion
          <li><a href="#9.0.0-removed-plugins">Removed ObserceChanges plugin</a></li>
          <li><a href="#9.0.0-removed-plugins">Removed HeaderTooltip plugin</a></li>
```
Is easier to skim through the breaking changes and does not trigger a panic attack "which ones???!!" ;)

2021-06-01 10:15 UTC, wojciechczerniak commented on tutorials/migration-guide.html
> +        to version <code>9.0.0+</code>.</p>
We should elaborate more on "why". Since v8.0.0 there are methods to work with the sourceData and we do not recommend changing `data` by reference. ObserveChanges purpose was to sync those changes and it works but is a performance bottleneck to `diff` objects and may introduce bugs. A year has passed, everyone should have migrated by now

2021-06-01 10:16 UTC, merged